app.js, controllers/user.js, infra/encryption/index.js, models/user.js, package.json
Completed setting up of basic User Schema
=> Add basic User model

controllers/index.js, controllers/tag.js, models/index.js, models/tag.js
Made basic Tag schema in Models, Added routes file in controllers for tags, added create new Tag route.
=> Add Tag Schema And create new tag Route

controllers/tag.js
Route to get a single tag by its slug name
=>  Add /tag/slug Route #3

app.js, controllers/user.js, infra/encryption/index.js, infra/jwt/index.js, models/user.js, package.json
Changed user schema: 
Added relations with other models
In app.js : 
Changed /user to /users
In infra/jwt/index.js:
Added auth middleware
In infra/encryption/index.js : 
Added encryptPassword function,
Removed comparePassword and made it inline(Since it was just one line of code)
In controllers/user.js 
Added user routes
=> Update User schema and routes

controllers/chat.js, controllers/index.js, infra/WebSockets/index.js, models/chat.js, models/index.js
functionality not tested after revamp
=> #2 chat model and private chat revamp

.eslintrc.json, .gitignore, .prettierrc, app.js, controllers/user.js, middleware/auth.js, models/user.js, test/config.js, test/tag.js, test/user_after_login.js, test/user_register_login.js
#23 
Backend
Added tests for tags and user registration
=> Added tag and user tests

app.js
Corrected the static serving part
=> Serve frontend only in production

infra/webSockets.js, middleware/auth.js, models/user.js, routes/chat.js
Tested chat api and made necessary changes with web sockets
=> Chat API test and SocketIO changes

controllers/forum.js
1.Forum posts filtering enabled on basis of required stuffs.
=> Add filtering of forum posts #22

controllers/forum.js, middleware/forumAuth.js, models/forum.js, test/config.js, test/forum.js, test/user_after_login.js
Backend  #57 
Add validation for parentId field
Rename poster filed -> author field
Update tests
Add tests for answer add
=> Revamp Forum Model

controllers/forum.js, controllers/tag.js
Added option to get the updated doc after updating in Forum and Tag module
=> Add {new:true} for all PUT/ routes #69

controllers/forum.js, models/forum.js, models/tag.js
Added feature of fuzzy serach in the getAll ("/ ") forums route.
It will return posts whose title or text  words matches the search string..
=> Add searching for forums #32

controllers/chat.js, infra/webSockets.js, package.json
Provided docs for the chat routes and the web sockets
=> Reference Documentation Provision for chat application

models/chat.js, models/index.js, models/notification.js
Created the Notification model  with dynamic reference for event_id based on model field.
=> Add:Notification model #95

app.js, controllers/forum.js, controllers/notifications.js, infra/webSockets.js, routes/index.js, routes/notifications.js
Notification routes and functions implementation for forum and chat notifications
=> Add notification routes

webapp/src/Components/Navbar/navbar.js, webapp/src/Components/Router/router.js, webapp/src/Pages/Edit Profile/editProfile.js, webapp/src/Pages/Homepage/home.js, webapp/src/Pages/Homepage/homepage.css, webapp/src/Pages/Login and Sign-up/register.js
**Improvements**
- Removed permanent sidebar from Homepage (it can be toggled)
- If you do not press enter after selecting a domain name (editProfile and Register) in the input and try to submit the form then you will be shown a warning alert to do the same.
- Added a button to add the selected Domain in edit profile and register because there was no way to press enter (newline) on a mobile device.
- Edited the success message in editProfile to inform the user to refresh the page to see updated avatar.
**Bug Fixes**
- Logout in sidebar now redirects to Homepage (Thanks Yashodhan for finding this bug)
=> Misc Improvements 

config/db.js, constants/notifications.js, controllers/forum.js, controllers/tag.js, controllers/user.js, infra/webSockets.js, models/user.js, routes/forum.js, routes/tag.js, routes/user.js
Added route to get all users as demanded by frontend member
=> Added new route and misc changes

webapp/src/Components/Navbar/navbar.js, webapp/src/Helpers/validateForm.js, webapp/src/Pages/Edit Profile/editProfile.js, webapp/src/Pages/Login and Sign-up/register.js
- Navbar now supports browser resizing after the window is loaded.
- Added form Validation for incomplete optional grouped fields (University Applied and Test Timeline). For example: If user enters the name of the Test but forgets to enter its score or date then he will be alerted to do so.
- Smoothed the scrolling effect which scrolls user to the field which fails validation
- Fixed a bug where pressing back button on internet browser to visit Homepage delayed the navbar from being hidden
- Removed a warning which appeared when clearing all Test Timeline inputs and adding a new one. (It occurred because an integer value ie. test score was initialized to null)
- The Add University and Add Test button are in-line with the height of their labels when all existing Tests/Universities are …
=> Improvements & Bug Fixes

webapp/src/App.js, webapp/src/Components/Navbar/navbar.js, webapp/src/Helpers/fetchRequests.js, webapp/src/Helpers/validateForm.js, webapp/src/Pages/Edit Profile/editProfile.js, webapp/src/Pages/Login and Sign-up/login.js, webapp/src/Pages/Login and Sign-up/register.js
Credits: @vixrant for the suggestion
- User details are now stored in localStorage at the time of Login instead of being fetched from API whenever required.
- The locally stored details will be updated whenever the user edits his profile details.
- Tags are now cached in localStorage and are updated in 3 scenarios:
1. When we encounter a new tag id which isn't present in our localStorage. 
2. When the user logs out or is forced to log out after his refreshToken Cookie expires (1 week after login).
3. When a user tries to Register a new account (Updated in this case so he gets a new updated list of all Universities)
- If by any chance the user's localStorage is deleted after he is logged in (Could occur when the user clears his browser data), the app will fetch his details and tags from …
=> Improve App Performance

webapp/package-lock.json, webapp/package.json, webapp/src/Pages/Homepage/home.js, webapp/src/Pages/Login and Sign-up/register.js
- Animated Homepage with Animate On Scroll Library
- Minor Bug fix where tags are refreshed each time a user visits register page
- Fixed a few vulnerabilities in webapp by npm audit fix
=> Animate Homepage with AOS library

controllers/forum.js
For latest and recommended post fetch only questions : added isAnswer=false flag while fetching
=> ADD:fetch only questions for recommended and latest
